name: Automated Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # once a day

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Install deps
      run: pip3 install -r requirements.txt
      
    - name: Update Process
      run: python3 modules_tracker.py